apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/barrozz/argo-crm-ARM-compliant.git
    targetRevision: HEAD
    chart: crm
    # path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true